### ISSUE TITLE
Incorrect spellings in README

### ISSUE THREAD

**Issue by avishkar7** [sl1mSha4dey/openMeet_Classe03#143]
...and if you are really interested in knowing all the ~~engigneering~~ (engineering*) process 

Under 
## "Not Only Code"
~~Submit~~ (Submitting*) code is not the only way you can contribute to this repository. If you are not familiar with the ~~tecnologies~~ (technologies*) used in this project but want to contribute to it, you still can!

**Comment by YuriBrandi** [comment]
Thank you, that file was overlooked and obviously poorly written.
